DROP TABLE reviews;

CREATE TABLE reviews (
	id SERIAL NOT NULL PRIMARY KEY,
	user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	product_id INT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
	comment TEXT NOT NULL,
	star SMALLINT NOT NULL
);